### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-terminal#135]
sponnet and flurkel need to talk about routing

**Comment by kingflurkel** [comment]
?

**Comment by kikipluche** [comment]
@kingflurkel yes, faffy mentioned this this morning and i've put this on the issues, because there needs to be some changes, and it needs to be talked through.

**Comment by kikipluche** [comment]
will be fixes on sc-boardwalk

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/sc-boardwalk#37
