### ISSUE TITLE
Persistent error message

### ISSUE THREAD

**Issue by wfe8006** [swarmcity/sc-terminal#62]
So I try to upload an invalid ARC wallet and the page shows the related error message. But then after I click exit and enter the same page again from home, I still see the error message.

![sc](https://cloud.githubusercontent.com/assets/9424330/22471933/004e6ddc-e80f-11e6-9cfe-2aeec89e2029.gif)

**Comment by faffydee** [comment]
(How old is this issue? The video suggests it is from a previous version)
@kiki, can you tell me where exact the message remains? 'Cause I already fixed one of those, so I need to know if there are more that I forgot.

**Comment by wfe8006** [comment]
Not sure if I have the latest link:

https://ipfs.swarm.city/ipfs/QmWkkVMwjUFdBkykHA6Tf3NpCj6aqrYzvjWVkEkA8SZsAY/#/intro/welcome

At least it didn't work yesterday.

**Comment by kikipluche** [comment]
@sotisoti thanks for the issue, I will look at it and prioritize it.

**Comment by kikipluche** [comment]
@sotisoti the latest link is in the terminaltesters channel on slack, but we will release a new link very soon, so you can wait for that one.

**Comment by kikipluche** [comment]
@sotisoti is fixed in new version, just checked.
