### ISSUE TITLE
change copy

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-terminal#92]
<img width="355" alt="screen shot 2017-02-08 at 10 50 22" src="https://cloud.githubusercontent.com/assets/9036081/22731884/886b3c4e-edec-11e6-99b4-d1670bb37677.png">
<img width="418" alt="screen shot 2017-02-07 at 14 57 36" src="https://cloud.githubusercontent.com/assets/9036081/22694001/d1086816-ed45-11e6-8167-b754c60c951c.png">
<img width="322" alt="screen shot 2017-02-08 at 10 58 59" src="https://cloud.githubusercontent.com/assets/9036081/22732228/acae0cf2-eded-11e6-9162-1cddb9b9434f.png">

**Comment by sponnet** [comment]
Fixed this.

<img width="482" alt="screen shot 2017-02-09 at 18 33 54" src="https://cloud.githubusercontent.com/assets/596726/22795387/d491e266-eef6-11e6-8df9-85653ff6ffb2.png">

and in token transfer too 

<img width="479" alt="screen shot 2017-02-09 at 18 51 00" src="https://cloud.githubusercontent.com/assets/596726/22795935/c16f19ea-eef8-11e6-961b-2927adf93e5e.png">
