### ISSUE TITLE
filling in username

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-terminal#96]
why is it first nickname that i have to delete before entering my name, instead of having it as username that when you start typing, verdwijnt.
<img width="432" alt="screen shot 2017-02-07 at 15 44 30" src="https://cloud.githubusercontent.com/assets/9036081/22695855/8b7703aa-ed4c-11e6-850a-5070b97074be.png">

**Comment by faffydee** [comment]
Because what you describe is impossible: we need a string to start with. You will always have to delete that first, before entering your own. Once we have a new default avatar we will put his "name" there as a default.
