### ISSUE TITLE
different feedback receiver versus sender

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-terminal#97]
one has you've succesfully send 1 SWT, the other one gets you received 1.00 tokens.
Why not say you received 1 SWT ?
<img width="1344" alt="screen shot 2017-02-07 at 15 49 03" src="https://cloud.githubusercontent.com/assets/9036081/22696057/191f78ea-ed4d-11e6-9fa4-7091771d6f01.png">

**Comment by faffydee** [comment]
DONE!
